<?php

declare(strict_types=1);

namespace Igor\Blog\Model;

use Magento\Framework\Model\AbstractModel;

class Post extends AbstractModel
{
    protected function _construct()
    {
        $this->init(\Igor\Blog\Model\ResourceModel\Post::class);
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}
